  version: '3'
  services:
    db:
      image: postgres:13-alpine
      ports:
        - ${POSTGRES_ADDRESS:-127.0.0.1:5432}:5432
      environment:
        - PGPORT=5432
        - POSTGRES_PASSWORD=engine
        - POSTGRES_USER=engine
        - POSTGRES_DB=engine
    php-fpm:
      build:
        context: ./.docker/php
        dockerfile: ./Dockerfile
      hostname: php-fpm
      volumes:
        - "./:/var/www/html"
        - './.docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf'
      working_dir: "/var/www/html"
      ports:
        - '8080:80'
